config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root :to => "home#index"

  resources :users
  resources :addresses, only: [:edit, :update, :show, :index, :new, :create, :destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  validates :zip_code, uniqueness: true, format: { with: /\A\d{5}-\d{3}\z/, message: "deve estar no formato xxxxx-xxx" }
  validates :zip_code, :street, :neighborhood, :number, :city, :state, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ['zip_code']
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update]

  def index
    @query = Address.all.order(created_at: :desc).ransack(params[:q])

    @addresses = @query.result
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)

    if @address.save
      redirect_to(addresses_path, notice: 'Criado com sucesso')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      redirect_to @address, notice: 'Endereço atualizado com sucesso.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @address = Address.find(params[:id])

    if @address.destroy
      redirect_to(addresses_path, notice: 'Excluído com sucesso')
    else
      redirect_to(addresses_path, notice: 'Não foi possível excluir')
    end
  end

  private

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address)
          .permit(:zip_code, :street, :neighborhood, :number, :city, :state, :complement)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to(users_path, notice: 'Excluído com sucesso')
    else
      redirect_to(users_path, notice: 'Não foi possível excluir')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/components/_form.html.erb
<div class="field">
  <%= form.label :zip_code, "CEP" %>
  <%= form.text_field :zip_code, size: 9, maxlength: 9, pattern: "\\d{5}-\\d{3}", placeholder: "57081-555" %>
</div>

<div class="field">
  <%= form.label :street, "Rua/avenida" %>
  <%= form.text_field :street %>
</div>

<div class="field">
  <%= form.label :number, "Número" %>
  <%= form.text_field :number %>
</div>

<div class="field">
  <%= form.label :neighborhood, "Bairro" %>
  <%= form.text_field :neighborhood %>
</div>

<div class="field">
  <%= form.label :city, "Cidade" %>
  <%= form.text_field :city %>
</div>

<div class="field">
  <%= form.label :state, "Estado" %>
  <%= form.text_field :state %>
</div>

<div class="field">
  <%= form.label :complement, "Complemento" %>
  <%= form.text_field :complement %>
</div>

<div class="actions">
  <%= form.submit "Salvar" %>
</div>

app/views/addresses/edit.html.erb
<div class="clearfix"></div>

<%= render partial: 'layouts/components/errors', locals: { resource: @address } %>

<%= form_with(model: @address, local: true) do |form| %>
  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :zip_code, "CEP", class: "form-label" %>
      <%= form.text_field :zip_code, class: "form-control", placeholder: "Digite o CEP" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :street, "Rua/Avenida", class: "form-label" %>
      <%= form.text_field :street, class: "form-control", placeholder: "Digite a Rua/Avenida" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :number, "Número", class: "form-label" %>
      <%= form.text_field :number, class: "form-control", placeholder: "Digite o Número" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :neighborhood, "Bairro", class: "form-label" %>
      <%= form.text_field :neighborhood, class: "form-control", placeholder: "Digite o Bairro" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :city, "Cidade", class: "form-label" %>
      <%= form.text_field :city, class: "form-control", placeholder: "Digite a Cidade" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :state, "Estado", class: "form-label" %>
      <%= form.text_field :state, class: "form-control", placeholder: "Digite o Estado" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :complement, "Complemento", class: "form-label" %>
      <%= form.text_field :complement, class: "form-control", placeholder: "Digite o Complemento" %>
    </div>
  </div>

  <div class="row mb-4" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= button_tag "Salvar", class: 'btn btn-custom' %>
      <%= link_to 'Voltar', addresses_path, class: 'btn btn-secondary ms-2' %>
    </div>
  </div>
<% end %>

app/views/addresses/index.html.erb
<h2 class="float-start mt-4" style="margin-right: 10px;">Endereços</h2>

<div class="float-end mt-4 me-3">
  <%= link_to(new_address_path, class: 'btn btn-custom') do %>
    <i class="bi bi-plus-lg"></i> Criar um novo endereço
  <% end %>
</div>

<div class="clearfix"></div>

<%= search_form_for(@query, url: addresses_path) do |form| %>
  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :zip_code_cont, "CEP", class: "form-label" %>
      <%= form.text_field :zip_code_cont, placeholder: "Busque pelo CEP", class: "form-control" %>
    </div>
  </div>
  <div class="row mb-4" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= link_to(url_for, class: 'btn btn-secondary me-2') do %>
        Limpar
      <% end %>
      <%= button_tag(class: 'btn btn-custom') do %>
        Buscar
      <% end %>
    </div>
  </div>
<% end %>

<table class="table table-striped table-hover table-bordered">
  <thead style="background-color: #7D5B8C; color: white;">
    <tr>
      <th style="background-color: #7D5B8C; color: white;">CEP</th>
      <th style="background-color: #7D5B8C; color: white;">Rua/Avenida</th>
      <th style="background-color: #7D5B8C; color: white;">Número</th>
      <th style="background-color: #7D5B8C; color: white;">Bairro</th>
      <th style="background-color: #7D5B8C; color: white;">Cidade</th>
      <th style="background-color: #7D5B8C; color: white;">Estado</th>
      <th style="background-color: #7D5B8C; color: white;">Complemento</th>
      <th style="background-color: #7D5B8C; color: white;">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @addresses.each do |address| %>
      <tr style="background-color: #7D5B8C; color: white;">
        <td><%= address.zip_code %></td>
        <td><%= address.street %></td>
        <td><%= address.number %></td>
        <td><%= address.neighborhood %></td>
        <td><%= address.city %></td>
        <td><%= address.state %></td>
        <td><%= address.complement %></td>
        <td>
          <%= link_to('<i class="bi bi-trash"></i>'.html_safe, address_path(address), class: 'btn btn-sm', data: { turbo_method: :delete, turbo_confirm: "Deseja excluir?" }) %>
          <%= link_to('<i class="bi bi-pencil"></i>'.html_safe, edit_address_path(address), class: 'btn btn-sm') %>
          <%= link_to('<i class="bi bi-info-circle"></i>'.html_safe, address_path(address), class: 'btn btn-sm') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="clearfix"></div>

app/views/addresses/new.html.erb
<%= render partial: 'layouts/components/errors', locals: { resource: @address } %>

<%= form_with(model: @address, local: true) do |form| %>
  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :zip_code, "CEP", class: "form-label" %>
      <%= form.text_field :zip_code, class: "form-control", placeholder: "Digite o CEP" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :street, "Rua/Avenida", class: "form-label" %>
      <%= form.text_field :street, class: "form-control", placeholder: "Digite a Rua/Avenida" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :number, "Número", class: "form-label" %>
      <%= form.text_field :number, class: "form-control", placeholder: "Digite o Número" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :neighborhood, "Bairro", class: "form-label" %>
      <%= form.text_field :neighborhood, class: "form-control", placeholder: "Digite o Bairro" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :city, "Cidade", class: "form-label" %>
      <%= form.text_field :city, class: "form-control", placeholder: "Digite a Cidade" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :state, "Estado", class: "form-label" %>
      <%= form.text_field :state, class: "form-control", placeholder: "Digite o Estado" %>
    </div>
  </div>

  <div class="row mb-3" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= form.label :complement, "Complemento", class: "form-label" %>
      <%= form.text_field :complement, class: "form-control", placeholder: "Digite o Complemento" %>
    </div>
  </div>

  <div class="row mb-4" style="margin-left: 10px;">
    <div class="col-md-6">
      <%= button_tag "Salvar", class: 'btn btn-custom' %>
      <%= link_to 'Voltar', addresses_path, class: 'btn btn-secondary ms-2' %>
    </div>
  </div>
<% end %>

app/views/addresses/show.html.erb
<div class="float-end mt-4 me-3">
  <%= link_to 'Voltar', addresses_path, class: 'btn btn-secondary' %>
</div>

<div class="clearfix"></div>

<table class="table table-striped table-hover table-bordered mt-4">
  <thead>
    <tr>
      <th>ID</th>
      <td><%= @address.id %></td>
    </tr>
    <tr>
      <th>CEP</th>
      <td><%= @address.zip_code %></td>
    </tr>
    <tr>
      <th>Rua/Avenida</th>
      <td><%= @address.street %></td>
    </tr>
    <tr>
      <th>Número</th>
      <td><%= @address.number %></td>
    </tr>
    <tr>
      <th>Bairro</th>
      <td><%= @address.neighborhood %></td>
    </tr>
    <tr>
      <th>Cidade</th>
      <td><%= @address.city %></td>
    </tr>
    <tr>
      <th>Estado</th>
      <td><%= @address.state %></td>
    </tr>
    <tr>
      <th>Complemento</th>
      <td><%= @address.complement %></td>
    </tr>
  </thead>
</table>

<div class="clearfix"></div>

app/views/home/index.html.erb
<div class="container text-center mt-5">
  <h1 class="display-4 mb-4">Bem-vindo ao Addresses!</h1>
  <p class="lead mb-4">O gerenciador de endereços que facilita a sua vida!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Addresses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css", media: "all" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "addresses/addresses.css", media: "all" %>
    <%= stylesheet_link_tag "users/users", media: "all" %>
    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if current_user.present? %>
      <nav class="navbar navbar-expand-lg" style="background-color: #7D5B8C;">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="justify-content: center; flex-grow: 1;">
              <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to 'Usuários', users_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to 'Endereços', addresses_path, class: 'nav-link text-white' %></li>
              <li class="nav-item"><%= link_to 'Sair', destroy_user_session_path, class: 'nav-link text-white' %></li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
    <% flash.each do |type, message| %>
      <div class="alert <%= type == 'notice' ? 'alert-success' : 'alert-danger' %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>

    <footer class="bg-light text-center py-3">
      <div class="container">
        <p class="mb-1">Siga-nos nas redes sociais:</p>
        <p class="mb-1">@Addresses_END</p>

        <div class="social-icons">
          <a href="https://www.instagram.com" target="_blank" class="text-dark me-3">
            <i class="fab fa-instagram fa-lg"></i>
          </a>
          <a href="https://wa.me/yourphonenumber" target="_blank" class="text-dark me-3">
            <i class="fab fa-whatsapp fa-lg"></i>
          </a>
        </div>
        <p class="mb-0">&copy; www.addresses.com.br</p>
      </div>
    </footer>

    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js", "data-turbo-track": "reload" %>
  </body>
</html>

app/views/layouts/components/_errors.html.erb
<% if resource.errors.any? %>
  <div style="margin-bottom: 10px;">
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<h2 class="float-start mt-4" style="margin-right: 10px;">Usuários</h2>

<div class="clearfix"></div>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Data de Criação</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
        <td>
          <%= link_to('<i class="bi bi-trash"></i>'.html_safe, user_path(user), class: 'btn btn-sm', data: { turbo_method: :delete, turbo_confirm: "Deseja excluir?" }) %>
          <%= link_to('<i class="bi bi-info-circle"></i>'.html_safe, user_path(user), class: 'btn btn-sm') %> <!-- Cor do botão detalhes -->
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="clearfix"></div>

app/views/users/show.html.erb
<h2>Usuário</h2>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Data de criação</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.id %></td>
        <td><%= @user.email %></td>
        <td><%= @user.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Voltar', users_path, class: 'btn btn-secondary' %>

<style>
  .table {
    width: 100%;
    border-collapse: collapse;
    background-color: #ffffff; /* Cor de fundo da tabela */
  }

  .table th {
    background-color: #7D5B8C; /* Cor do cabeçalho */
    color: #ffffff; /* Cor do texto do cabeçalho */
  }

  .table td {
    padding: 10px;
  }

  .table tr:nth-child(even) {
    background-color: #f9f9f9; /* Cor das linhas pares */
  }

  .table-responsive {
    margin-top: 20px; /* Espaçamento superior */
  }
</style>